/**
 * Session Model
 * 
 * Represents a binaural beat session with user preferences and results
 */

import mongoose from 'mongoose';

const sessionSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    
    status: {
      type: String,
      enum: ['active', 'paused', 'ended', 'error'],
      default: 'active',
    },
    
    preferences: {
      intent: {
        type: String,
        enum: [
          'sleep',
          'rest',
          'meditation',
          'mindfulness',
          'focus',
          'deep_focus',
          'creative_work',
          'creativity',
          'light_focus',
        ],
        default: 'focus',
      },
      coordinates: {
        lat: Number,
        lng: Number,
      },
      locationHint: String,
    },
    
    context: {
      type: mongoose.Schema.Types.Mixed,
      // Stores the context generated by Context Agent
    },
    
    strategy: {
      type: mongoose.Schema.Types.Mixed,
      // Stores the strategy selected by Strategy Agent
    },
    
    plan: {
      type: mongoose.Schema.Types.Mixed,
      // Stores the plan generated by Generation Agent
    },
    
    policyResult: {
      allowed: Boolean,
      violations: [mongoose.Schema.Types.Mixed],
      warnings: [mongoose.Schema.Types.Mixed],
    },
    
    startedAt: {
      type: Date,
      default: Date.now,
    },
    
    endedAt: {
      type: Date,
    },
    
    duration: {
      type: Number, // in seconds
    },
    
    feedback: {
      effectiveness: {
        type: Number,
        min: 1,
        max: 5,
      },
      notes: String,
    },
  },
  {
    timestamps: true,
  }
);

// Index for querying user sessions
sessionSchema.index({ userId: 1, startedAt: -1 });

// Virtual for session duration
sessionSchema.virtual('actualDuration').get(function () {
  if (this.endedAt && this.startedAt) {
    return Math.floor((this.endedAt - this.startedAt) / 1000);
  }
  return null;
});

// Method to end session
sessionSchema.methods.endSession = function () {
  this.status = 'ended';
  this.endedAt = new Date();
  this.duration = this.actualDuration;
  return this.save();
};

const Session = mongoose.model('Session', sessionSchema);

export default Session;
